In [24]:
import pandas as pd 
import os
import random
import numpy as np

In [2]:
repeat0 = 10
repeat1 = 1000

In [24]:
code = rf"""

; ------------------------------------
; Author: Hosein Yavarzadeh 
; Email: hyavarzadeh@ucsd.edu
; Supervisor: Prof. Dean Tullsen
; ------------------------------------

%define repeat0  {repeat0}             ; Number of repetitions of whole test. Default = 8
%define repeat1  {repeat1}           ; Repeat count for loop around testcode. Default = no loop
%define repeat2  1              ; Repeat count for repeat macro around testcode. Default = 100

%macro testinitc 0              ; Macro to call in each test before reading counters.
    mov dword[PrintCustomPMC], 1
    mov ebx, 8000             
    lea rdi, [UserData]
    rand_loop:
    rdrand eax
    and eax, 1
    mov [rdi], al
    inc rdi
    dec ebx
    jnz rand_loop

%endmacro

%macro testinit2 0              ; Macro with initializations before each test. Default = nothing
    lea rdi, [UserData]
%endmacro

%macro testcode 0               ; A multi-line macro executing any piece of test code.

    inc rdi

    cmp byte[rdi],0
    
    ; dummy_branch 300, 0

    ; jmp rand_branch
    mov rax, 0x100000000
    mov rbx, rand_branch_back
    mov rdx, 200
    mov rcx, 0
    cmp rcx, 0
    jmp rax
    rand_branch_back:

    dummy_branch var, 5

    ; test branch
    READ_PMC_START
    cmp byte[rdi],0
    je target2
    target2:
    READ_PMC_END

%endmacro

%macro dummy_branch 2
      mov rax, 0
      %assign i (100)*(%2)
      %assign j (100)*(%2)
      %rep %1
            %assign j i+1
            label%+ i:
            cmp rax, 0
            je label%+ j 
            %assign i j  
      %endrep
    ;   align (1 << my_align)
      label%+ j:
%endmacro

"""

In [25]:
ld_script = r"""
/* Script for -z combreloc -z separate-code */
/* Copyright (C) 2014-2020 Free Software Foundation, Inc.
   Copying and distribution of this script, with or without modification,
   are permitted in any medium without royalty provided the copyright
   notice and this notice are preserved.  */
OUTPUT_FORMAT("elf64-x86-64", "elf64-x86-64",
	      "elf64-x86-64")
OUTPUT_ARCH(i386:x86-64)
ENTRY(_start)
SEARCH_DIR("=/usr/local/lib/x86_64-linux-gnu"); SEARCH_DIR("=/lib/x86_64-linux-gnu"); SEARCH_DIR("=/usr/lib/x86_64-linux-gnu"); SEARCH_DIR("=/usr/lib/x86_64-linux-gnu64"); SEARCH_DIR("=/usr/local/lib64"); SEARCH_DIR("=/lib64"); SEARCH_DIR("=/usr/lib64"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib"); SEARCH_DIR("=/usr/x86_64-linux-gnu/lib64"); SEARCH_DIR("=/usr/x86_64-linux-gnu/lib");
SECTIONS
{
  PROVIDE (__executable_start = SEGMENT_START("text-segment", 0x400000)); . = SEGMENT_START("text-segment", 0x400000) + SIZEOF_HEADERS;
  .interp         : { *(.interp) }
  .note.gnu.build-id  : { *(.note.gnu.build-id) }
  .hash           : { *(.hash) }
  .gnu.hash       : { *(.gnu.hash) }
  .dynsym         : { *(.dynsym) }
  .dynstr         : { *(.dynstr) }
  .gnu.version    : { *(.gnu.version) }
  .gnu.version_d  : { *(.gnu.version_d) }
  .gnu.version_r  : { *(.gnu.version_r) }
  .rela.dyn       :
    {
      *(.rela.init)
      *(.rela.text .rela.text.* .rela.gnu.linkonce.t.*)
      *(.rela.fini)
      *(.rela.rodata .rela.rodata.* .rela.gnu.linkonce.r.*)
      *(.rela.data .rela.data.* .rela.gnu.linkonce.d.*)
      *(.rela.tdata .rela.tdata.* .rela.gnu.linkonce.td.*)
      *(.rela.tbss .rela.tbss.* .rela.gnu.linkonce.tb.*)
      *(.rela.ctors)
      *(.rela.dtors)
      *(.rela.got)
      *(.rela.bss .rela.bss.* .rela.gnu.linkonce.b.*)
      *(.rela.ldata .rela.ldata.* .rela.gnu.linkonce.l.*)
      *(.rela.lbss .rela.lbss.* .rela.gnu.linkonce.lb.*)
      *(.rela.lrodata .rela.lrodata.* .rela.gnu.linkonce.lr.*)
      *(.rela.ifunc)
    }
  .rela.plt       :
    {
      *(.rela.plt)
      PROVIDE_HIDDEN (__rela_iplt_start = .);
      *(.rela.iplt)
      PROVIDE_HIDDEN (__rela_iplt_end = .);
    }
  . = ALIGN(CONSTANT (MAXPAGESIZE));
  .init           :
  {
    KEEP (*(SORT_NONE(.init)))
  }
  .plt            : { *(.plt) *(.iplt) }
.plt.got        : { *(.plt.got) }
.plt.sec        : { *(.plt.sec) }
  . = 0x40000000;
  .text           :
  {
    b64.o (.text .stub .text.* .gnu.linkonce.t.*)
    *(.text.unlikely .text.*_unlikely .text.unlikely.*)
    *(.text.exit .text.exit.*)
    *(.text.startup .text.startup.*)
    *(.text.hot .text.hot.*)
    *(SORT(.text.sorted.*))
    a64.o (.text .stub .text.* .gnu.linkonce.t.*)
    /* .gnu.warning sections are handled specially by elf.em.  */
    *(.gnu.warning)
  }
  .fini           :
  {
    KEEP (*(SORT_NONE(.fini)))
  }
  PROVIDE (__etext = .);
  PROVIDE (_etext = .);
  PROVIDE (etext = .);
  . = ALIGN(CONSTANT (MAXPAGESIZE));
  /* Adjust the address for the rodata segment.  We want to adjust up to
     the same address within the page on the next page up.  */
  . = SEGMENT_START("rodata-segment", ALIGN(CONSTANT (MAXPAGESIZE)) + (. & (CONSTANT (MAXPAGESIZE) - 1)));
  .rodata         : { *(.rodata .rodata.* .gnu.linkonce.r.*) }
  .rodata1        : { *(.rodata1) }
  .eh_frame_hdr   : { *(.eh_frame_hdr) *(.eh_frame_entry .eh_frame_entry.*) }
  .eh_frame       : ONLY_IF_RO { KEEP (*(.eh_frame)) *(.eh_frame.*) }
  .gcc_except_table   : ONLY_IF_RO { *(.gcc_except_table .gcc_except_table.*) }
  .gnu_extab   : ONLY_IF_RO { *(.gnu_extab*) }
  /* These sections are generated by the Sun/Oracle C++ compiler.  */
  .exception_ranges   : ONLY_IF_RO { *(.exception_ranges*) }
  /* Adjust the address for the data segment.  We want to adjust up to
     the same address within the page on the next page up.  */
  . = DATA_SEGMENT_ALIGN (CONSTANT (MAXPAGESIZE), CONSTANT (COMMONPAGESIZE));
  /* Exception handling  */
  .eh_frame       : ONLY_IF_RW { KEEP (*(.eh_frame)) *(.eh_frame.*) }
  .gnu_extab      : ONLY_IF_RW { *(.gnu_extab) }
  .gcc_except_table   : ONLY_IF_RW { *(.gcc_except_table .gcc_except_table.*) }
  .exception_ranges   : ONLY_IF_RW { *(.exception_ranges*) }
  /* Thread Local Storage sections  */
  .tdata	  :
   {
     PROVIDE_HIDDEN (__tdata_start = .);
     *(.tdata .tdata.* .gnu.linkonce.td.*)
   }
  .tbss		  : { *(.tbss .tbss.* .gnu.linkonce.tb.*) *(.tcommon) }
  .preinit_array    :
  {
    PROVIDE_HIDDEN (__preinit_array_start = .);
    KEEP (*(.preinit_array))
    PROVIDE_HIDDEN (__preinit_array_end = .);
  }
  .init_array    :
  {
    PROVIDE_HIDDEN (__init_array_start = .);
    KEEP (*(SORT_BY_INIT_PRIORITY(.init_array.*) SORT_BY_INIT_PRIORITY(.ctors.*)))
    KEEP (*(.init_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .ctors))
    PROVIDE_HIDDEN (__init_array_end = .);
  }
  .fini_array    :
  {
    PROVIDE_HIDDEN (__fini_array_start = .);
    KEEP (*(SORT_BY_INIT_PRIORITY(.fini_array.*) SORT_BY_INIT_PRIORITY(.dtors.*)))
    KEEP (*(.fini_array EXCLUDE_FILE (*crtbegin.o *crtbegin?.o *crtend.o *crtend?.o ) .dtors))
    PROVIDE_HIDDEN (__fini_array_end = .);
  }
  .ctors          :
  {
    /* gcc uses crtbegin.o to find the start of
       the constructors, so we make sure it is
       first.  Because this is a wildcard, it
       doesn't matter if the user does not
       actually link against crtbegin.o; the
       linker won't look for a file to match a
       wildcard.  The wildcard also means that it
       doesn't matter which directory crtbegin.o
       is in.  */
    KEEP (*crtbegin.o(.ctors))
    KEEP (*crtbegin?.o(.ctors))
    /* We don't want to include the .ctor section from
       the crtend.o file until after the sorted ctors.
       The .ctor section from the crtend file contains the
       end of ctors marker and it must be last */
    KEEP (*(EXCLUDE_FILE (*crtend.o *crtend?.o ) .ctors))
    KEEP (*(SORT(.ctors.*)))
    KEEP (*(.ctors))
  }
  .dtors          :
  {
    KEEP (*crtbegin.o(.dtors))
    KEEP (*crtbegin?.o(.dtors))
    KEEP (*(EXCLUDE_FILE (*crtend.o *crtend?.o ) .dtors))
    KEEP (*(SORT(.dtors.*)))
    KEEP (*(.dtors))
  }
  .jcr            : { KEEP (*(.jcr)) }
  .data.rel.ro : { *(.data.rel.ro.local* .gnu.linkonce.d.rel.ro.local.*) *(.data.rel.ro .data.rel.ro.* .gnu.linkonce.d.rel.ro.*) }
  .dynamic        : { *(.dynamic) }
  .got            : { *(.got) *(.igot) }
  . = DATA_SEGMENT_RELRO_END (SIZEOF (.got.plt) >= 24 ? 24 : 0, .);
  .got.plt        : { *(.got.plt) *(.igot.plt) }
  .data           :
  {
    *(.data .data.* .gnu.linkonce.d.*)
    SORT(CONSTRUCTORS)
  }
  .data1          : { *(.data1) }
  _edata = .; PROVIDE (edata = .);
  . = .;
  __bss_start = .;
  .bss            :
  {
   *(.dynbss)
   *(.bss .bss.* .gnu.linkonce.b.*)
   *(COMMON)
   /* Align here to ensure that the .bss section occupies space up to
      _end.  Align after .bss to ensure correct alignment even if the
      .bss section disappears because there are no input sections.
      FIXME: Why do we need it? When there is no .bss section, we do not
      pad the .data section.  */
   . = ALIGN(. != 0 ? 64 / 8 : 1);
  }
  .lbss   :
  {
    *(.dynlbss)
    *(.lbss .lbss.* .gnu.linkonce.lb.*)
    *(LARGE_COMMON)
  }
  . = ALIGN(64 / 8);
  . = SEGMENT_START("ldata-segment", .);
  .lrodata   ALIGN(CONSTANT (MAXPAGESIZE)) + (. & (CONSTANT (MAXPAGESIZE) - 1)) :
  {
    *(.lrodata .lrodata.* .gnu.linkonce.lr.*)
  }
  .ldata   ALIGN(CONSTANT (MAXPAGESIZE)) + (. & (CONSTANT (MAXPAGESIZE) - 1)) :
  {
    *(.ldata .ldata.* .gnu.linkonce.l.*)
    . = ALIGN(. != 0 ? 64 / 8 : 1);
  }
  . = ALIGN(64 / 8);
  _end = .; PROVIDE (end = .);
  . = DATA_SEGMENT_END (.);
  /* Stabs debugging sections.  */
  .stab          0 : { *(.stab) }
  .stabstr       0 : { *(.stabstr) }
  .stab.excl     0 : { *(.stab.excl) }
  .stab.exclstr  0 : { *(.stab.exclstr) }
  .stab.index    0 : { *(.stab.index) }
  .stab.indexstr 0 : { *(.stab.indexstr) }
  .comment       0 : { *(.comment) }
  .gnu.build.attributes : { *(.gnu.build.attributes .gnu.build.attributes.*) }
  /* DWARF debug sections.
     Symbols in the DWARF debugging sections are relative to the beginning
     of the section so we begin them at 0.  */
  /* DWARF 1 */
  .debug          0 : { *(.debug) }
  .line           0 : { *(.line) }
  /* GNU DWARF 1 extensions */
  .debug_srcinfo  0 : { *(.debug_srcinfo) }
  .debug_sfnames  0 : { *(.debug_sfnames) }
  /* DWARF 1.1 and DWARF 2 */
  .debug_aranges  0 : { *(.debug_aranges) }
  .debug_pubnames 0 : { *(.debug_pubnames) }
  /* DWARF 2 */
  .debug_info     0 : { *(.debug_info .gnu.linkonce.wi.*) }
  .debug_abbrev   0 : { *(.debug_abbrev) }
  .debug_line     0 : { *(.debug_line .debug_line.* .debug_line_end) }
  .debug_frame    0 : { *(.debug_frame) }
  .debug_str      0 : { *(.debug_str) }
  .debug_loc      0 : { *(.debug_loc) }
  .debug_macinfo  0 : { *(.debug_macinfo) }
  /* SGI/MIPS DWARF 2 extensions */
  .debug_weaknames 0 : { *(.debug_weaknames) }
  .debug_funcnames 0 : { *(.debug_funcnames) }
  .debug_typenames 0 : { *(.debug_typenames) }
  .debug_varnames  0 : { *(.debug_varnames) }
  /* DWARF 3 */
  .debug_pubtypes 0 : { *(.debug_pubtypes) }
  .debug_ranges   0 : { *(.debug_ranges) }
  /* DWARF Extension.  */
  .debug_macro    0 : { *(.debug_macro) }
  .debug_addr     0 : { *(.debug_addr) }
  .gnu.attributes 0 : { KEEP (*(.gnu.attributes)) }
  /DISCARD/ : { *(.note.GNU-stack) *(.gnu_debuglink) *(.gnu.lto_*) }

"""

In [26]:
def create_nasm(cnt):
    nasm_new_sections = ''
    for i in range(cnt):
        nasm_new_sections += f"""
SECTION .dummy_branch_{i} exec
    dummy_label_{i}:
    je dummy_label_{i+1}

"""
    nasm_new_sections += f"""
SECTION .dummy_branch_{cnt} exec
    dummy_label_{cnt}:
    dec rdx
    cmp rdx, 0
    jmp dummy_label_{cnt+1}

SECTION .dummy_branch_{cnt+1} exec
    dummy_label_{cnt+1}:
    je dummy_label_{cnt+2}
    mov rax, 0x100000000
    mov rcx, 0
    cmp rcx, 0
    jmp rax

SECTION .dummy_branch_{cnt+2} exec
    dummy_label_{cnt+2}:
    cmp byte[rdi],0
    jmp dummy_label_{cnt+3}

SECTION .dummy_branch_{cnt+3} exec
    dummy_label_{cnt+3}:
    je dummy_label_{cnt+4}
    jmp dummy_label_{cnt+4}

SECTION .dummy_branch_{cnt+4} exec
    dummy_label_{cnt+4}:
    jmp rbx
"""
    with open("bp.nasm", "w") as file:
      file.write(code + nasm_new_sections)

In [27]:
def create_ld(a, b, cnt, stride=0x10000000):
  ld_new_sections = ''

  for i in range(cnt):
    ld_new_sections += f"""
    . = {hex(0x100000000 + i * stride)};
    .dummy_branch_{i} : {{ *(.dummy_branch_{i}) }}
  """

  # ld_new_sections += f"""
  #   . = {hex(0x100000000 + cnt * stride + ((1 << a) if a >= 0 else 0))};
  #   .dummy_branch_{cnt} : {{ *(.dummy_branch_{cnt}) }}
  # """

  # ld_new_sections += f"""
  #   . = {hex(0x100000000 + (cnt + 1) * stride + ((b << b) if a >= 0 else 0))};
  #   .dummy_branch_{cnt + 1} : {{ *(.dummy_branch_{cnt + 1}) }}
  # """
  
  b_addr = 0x100000000 + cnt * stride + random.randint(0, ((1 << a) if a >= 0 else 0))
  # b_addr = 0x100000000 + cnt * stride + a
  
  ld_new_sections += f"""
    . = {hex(b_addr)};
    .dummy_branch_{cnt} : {{ *(.dummy_branch_{cnt}) }}
  """
  
  t_addr = 0x100000000 + (cnt + 1) * stride + random.randint(0, ((1 << b) if b >= 0 else 0))
  # t_addr = 0x100000000 + (cnt + 1) * stride + b

  ld_new_sections += f"""
    . = {hex(t_addr)};
    .dummy_branch_{cnt + 1} : {{ *(.dummy_branch_{cnt + 1}) }}
  """

  ld_new_sections += '}'

  with open("script.ld", "w") as file:
      file.write(ld_script + ld_new_sections)
      
  return b_addr, t_addr

In [28]:
# rdx 5
cnt = 10
start = 10
end = 10

i = 26
j = 26

final_df = []
for sample_cnt in range(6000):
    create_nasm(cnt)
    b_addr, t_addr = create_ld(i, j, cnt + 3, 1 << 30)
    os.system(f"./run.sh {start} {end}")
    if sample_cnt % 50 == 0:
        print(sample_cnt)

    data = pd.read_csv("results.csv", comment='#', delim_whitespace=True)
    data["Clock"] = pd.to_numeric(data["Clock"],errors='coerce')
    data["BrRetired"] = pd.to_numeric(data["BrRetired"],errors='coerce')
    data["BrMispred"] = pd.to_numeric(data["BrMispred"],errors='coerce')
    data["Clock"] = (data["Clock"]) / repeat1
    data["BrRetired"] = data["BrRetired"] / repeat1
    data["BrMispred"] = data["BrMispred"] / repeat1
    final_df.append((data.groupby(data.index // repeat0).mean()["BrMispred"][0], b_addr, t_addr))

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
1900
1950
2000
2050
2100
2150
2200
2250
2300
2350
2400
2450
2500
2550
2600
2650
2700
2750
2800
2850
2900
2950
3000
3050
3100
3150
3200
3250
3300
3350
3400
3450
3500
3550
3600
3650
3700
3750
3800
3850
3900
3950
4000
4050
4100
4150
4200
4250
4300
4350
4400
4450
4500
4550
4600
4650
4700
4750
4800
4850
4900
4950
5000
5050
5100
5150
5200
5250
5300
5350
5400
5450
5500
5550
5600
5650
5700
5750
5800
5850
5900
5950


In [38]:
my_df = pd.DataFrame(final_df)

In [6]:
my_df = pd.read_pickle('./script8_1/1.pkl')

In [14]:
final_df = []
final_mis_df = []
final_pred_df = []
for i in range(6000):
    final_df.append((my_df[0][i], my_df[1][i], my_df[2][i]))
    if my_df[0][i] < 0.25:
        final_pred_df.append((my_df[0][i], my_df[1][i], my_df[2][i]))
    else:
        final_mis_df.append((my_df[0][i], my_df[1][i], my_df[2][i]))

In [56]:
hex(18273715772), hex(19376831460)

('0x44132c63c', '0x482f2fbe4')

In [54]:
final_pred_df

[(0.0004, 18273715772, 19376831460),
 (0.0004, 18269814331, 19365966702),
 (0.00030000000000000003, 18281182846, 19345658541),
 (0.00030000000000000003, 18263585343, 19392854835),
 (0.00030000000000000003, 18269593213, 19374419441),
 (0.00030000000000000003, 18254566781, 19357803406),
 (0.0004, 18300586239, 19329342189),
 (0.00030000000000000003, 18267013695, 19374928710),
 (0.00030000000000000003, 18266319419, 19374160514),
 (0.0004, 18291708926, 19345630751),
 (0.00030000000000000003, 18258915389, 19392411762),
 (0.00030000000000000003, 18273913535, 19349512712),
 (0.00030000000000000003, 18273949308, 19384382933),
 (0.0004, 18279032317, 19353045638),
 (0.00030000000000000003, 18307627196, 19335104100),
 (0.0004, 18271220733, 19385161344),
 (0.0005, 18263360443, 19379723141),
 (0.00030000000000000003, 18293186108, 19329102418),
 (0.0005, 18318486779, 19379782011),
 (0.00030000000000000003, 18308387836, 19368881305),
 (0.0004, 18276421308, 19353140645),
 (0.00030000000000000003, 18286

In [16]:
len(final_pred_df), len(final_mis_df)

(508, 5492)

In [38]:
pred_br_addr_bits = []
pred_tar_addr_bits = []
for _, br_addr, tar_addr in final_pred_df:
    pred_br_addr_bits.append([(1 if br_addr & (1 << i) != 0 else 0) for i in range(20)])
    pred_tar_addr_bits.append([(1 if tar_addr & (1 << i) != 0 else 0) for i in range(20)])
mis_br_addr_bits = []
mis_tar_addr_bits = []    
for _, br_addr, tar_addr in final_mis_df:
    mis_br_addr_bits.append([(1 if br_addr & (1 << i) != 0 else 0) for i in range(20)])
    mis_tar_addr_bits.append([(1 if tar_addr & (1 << i) != 0 else 0) for i in range(20)])

In [39]:
pred_br_addr_bits_np = np.array(pred_br_addr_bits)
pred_tar_addr_bits_np = np.array(pred_tar_addr_bits)

mis_br_addr_bits_np = np.array(mis_br_addr_bits)
mis_tar_addr_bits_np = np.array(mis_tar_addr_bits)

In [44]:
pred_br_addr_bits_np.sum(0) / len(final_pred_df)

array([0.62204724, 0.57874016, 0.80905512, 0.9980315 , 0.9980315 ,
       1.        , 0.47047244, 0.51181102, 0.48228346, 0.44488189,
       0.48818898, 0.49212598, 0.47834646, 0.51771654, 0.52559055,
       0.52165354, 0.47047244, 0.46456693, 0.48031496, 0.53149606])

In [45]:
mis_br_addr_bits_np.sum(0) / len(final_mis_df)

array([0.47723962, 0.48962127, 0.47177713, 0.46959213, 0.46176256,
       0.46631464, 0.50200291, 0.48780044, 0.50036417, 0.49089585,
       0.51474873, 0.51037873, 0.50072833, 0.50418791, 0.49162418,
       0.51110706, 0.49308084, 0.50091042, 0.50072833, 0.4925346 ])

In [46]:
pred_tar_addr_bits_np.sum(0) / len(final_pred_df)

array([0.48031496, 0.48818898, 0.49409449, 0.5019685 , 0.50393701,
       0.50393701, 0.48425197, 0.51771654, 0.48425197, 0.50590551,
       0.4507874 , 0.53937008, 0.50393701, 0.47244094, 0.51181102,
       0.50393701, 0.48228346, 0.49409449, 0.55511811, 0.52165354])

In [47]:
mis_tar_addr_bits_np.sum(0) / len(final_mis_df)

array([0.4989075 , 0.51857247, 0.50673707, 0.49799709, 0.49508376,
       0.49945375, 0.48361253, 0.49945375, 0.49198835, 0.48998543,
       0.51019665, 0.49635834, 0.50054625, 0.50619082, 0.49344501,
       0.51147123, 0.49817917, 0.50582666, 0.49526584, 0.49763292])

In [13]:
ccnntt = 0
for m, b, t in final_df:
    if m < .25:
        ccnntt += 1
        print(hex(b & 0x10), hex(t & 0x10))
print(ccnntt)

0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x0
0x10 0x0
0x10 0x0
0x10 0x10
0x10 0x10
0x10 0x0
0x10 0x10
0x10 0x10
